"""Constants for the risk-aware ETF allocation project."""

TOTAL_ALLOCATION = 100
ETFS_TO_SELECT = 5
EQUITIES_NEEDED = 3
BONDS_NEEDED = 1
GOLD_NEEDED = 1

EQUITY = "E"
BOND = "B"
GOLD = "G"

RETURN_POINTS_FACTOR = 4
STABILITY_BENCHMARK = 30
STABILITY_POINTS_FACTOR = 2
DIVERSIFICATION_POINTS_FACTOR = 0.5
